name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ##################################
  ## Windows
  ##################################
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.4"

      - name: Get dependencies
        run: flutter pub get

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows
        run: flutter build windows --release

      - name: List Release Folder
        shell: powershell
        run: |
          Write-Host "===== Release Folder ====="
          Get-ChildItem build/windows/x64/runner/Release -Recurse

      - name: Find EXE
        id: find_exe
        shell: powershell
        run: |
          $exe = Get-ChildItem build/windows/x64/runner/Release -Filter *.exe -Recurse | Select-Object -First 1

          if ($null -eq $exe) {
            Write-Error "No EXE file found!"
            exit 1
          }

          Write-Host "Found EXE: $($exe.FullName)"
          echo "exe_path=$($exe.FullName)" >> $env:GITHUB_OUTPUT

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_exe.outputs.exe_path }}

  ##################################
  ## macOS
  ##################################
  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.4"

      - run: flutter pub get

      - run: flutter config --enable-macos-desktop

      - run: flutter build macos --release

      # Install create-dmg
      - run: brew install create-dmg

      # Create DMG
      - name: Build DMG
        run: |
          mkdir dmg
          cp -R build/macos/Build/Products/Release/*.app dmg/

          create-dmg \
            --volname "Tray" \
            --window-pos 200 120 \
            --window-size 800 500 \
            --icon-size 100 \
            --app-drop-link 600 185 \
            Tray.dmg \
            dmg/

      - uses: softprops/action-gh-release@v2
        with:
          files: Tray.dmg