name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:

  ##################################
  ## Windows
  ##################################

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.4"

      - run: flutter pub get

      - run: flutter config --enable-windows-desktop

      - run: flutter build windows --release

      - name: Zip Windows Build
        shell: powershell
        run: |
          Compress-Archive `
            -Path build/windows/x64/runner/Release/* `
            -DestinationPath Windows.zip

      - uses: softprops/action-gh-release@v2
        with:
          files: Windows.zip

  ##################################
  ## macOS
  ##################################

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.4"

      - run: flutter pub get

      - run: flutter config --enable-macos-desktop

      - run: flutter build macos --release

      # Install create-dmg
      - run: brew install create-dmg

      # Create DMG
      - name: Build DMG
        run: |
          mkdir dmg

          cp -R build/macos/Build/Products/Release/*.app dmg/

          create-dmg \
            --volname "MyApp" \
            --window-pos 200 120 \
            --window-size 800 500 \
            --icon-size 100 \
            --app-drop-link 600 185 \
            MyApp.dmg \
            dmg/

      - uses: softprops/action-gh-release@v2
        with:
          files: MyApp.dmg